name: API-TEST-MINIKUBE

on:
  workflow_dispatch:
    inputs:
      test_module:
        description: 'TEST_MODULE file or path'
        required: true
        default: ''
      case_name:
        description: 'test case name'
        required: false
        default: 'api-test-minikube'
      branch_name:
        description: 'testinfra branch name'
        required: true
        default: 'main'
      release_version:
        description: 'kubeblocks release version'
        required: false
        default: 'latest'
      change_flag:
        description: '1:change wesql cd; 2:change wesql cd fixed passwd'
        required: false
        default: '1'

run-name: ${{ github.event.inputs.release_version }}:${{ github.event.inputs.case_name }}

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  GO_VERSION: '1.19'
  HELM_VERSION: 'v3.10.0'


jobs:
  minikube-api-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s: [ v1.25.5, v1.24.9, v1.23.15, v1.22.16 ]
    name: Minikube ${{matrix.k8s}}
    env:
      K8S: ${{ matrix.k8s }}
    steps:
      - name: install helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: start minikube
        uses: medyagh/setup-minikube@latest
        id: minikube
        with:
          kubernetes-version: ${{ matrix.k8s }}
          cache: false
          cpus: 2
          memory: 4096m

      - name: checkout testinfra
        uses: actions/checkout@v3
        with:
          repository: apecloud/testinfra
          ref: ${{ github.event.inputs.branch_name }}
          path: ./
          token: ${{ env.GITHUB_TOKEN }}

      - name: install dbaas
        run: |
          bash .github/utils/install-kubeblocks.sh ${{ github.event.inputs.release_version }}

      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.5.1
          go install github.com/onsi/gomega/...

      - name: run test
        run: |
          bash .github/utils/change-wesql-cd.sh \
            ./ ${{ github.event.inputs.change_flag }}
          
          make api-test TEST_MODULE=${{ github.event.inputs.test_module }}
