name: API-TEST-MINIKUBE

on:
  workflow_dispatch:
    inputs:
      test_module:
        description: 'TEST_MODULE file or path'
        required: true
        default: ''
      case_name:
        description: 'test case name'
        required: false
        default: 'api_test_minikube'
      branch_name:
        description: 'testinfra branch name'
        required: true
        default: 'main'
      release_version:
        description: 'kubeblocks release version'
        required: false
        default: 'latest'
      model:
        description: 'monitor:open monitor'
        required: false
        default: ''
      change_flag:
        description: '1:change wesql cd; 2:change wesql cd fixed passwd'
        required: false
        default: '1'

run-name: ${{ github.event.inputs.release_version }}:${{ github.event.inputs.case_name }}

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  GO_VERSION: '1.19'
  HELM_VERSION: 'v3.10.0'


jobs:
  minikube-api-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s: [ v1.26.1, v1.25.6, v1.24.10, v1.23.16, v1.22.17 ]
    name: minikube K8s ${{matrix.k8s}}
    env:
      K8S: ${{ matrix.k8s }}
    steps:
      - uses: actions/checkout@v3
      - name: install helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: checkout testinfra
        uses: actions/checkout@v3
        with:
          repository: apecloud/testinfra
          ref: ${{ github.event.inputs.branch_name }}
          path: testinfra
          token: ${{ env.GITHUB_TOKEN }}

      - name: install minikube k8s
        run: |
          cd testinfra
          bash ${{ github.workspace }}/testinfra/.github/utils/install-minikube.sh
          kubectl get nodes --show-labels

      - name: install dbaas
        run: |
          RELEASE_VERSION=`bash ${{ github.workspace }}/testinfra/.github/utils/release-version.sh ${{ env.GITHUB_TOKEN }} ${{ github.event.inputs.release_version }}`
          echo "RELEASE_VERSION:"$RELEASE_VERSION
          
          helm repo add kubeblocks https://apecloud.github.io/helm-charts
          
          MODEL=${{ github.event.inputs.model }}
          if [[ "$MODEL" == "monitor" ]]; then
            helm upgrade --install kubeblocks kubeblocks/kubeblocks \
              --version "$RELEASE_VERSION" \
              --set="prometheus.enabled=true" \
              --set="grafana.enabled=true" \
              --set="dashboards.enabled=true"
          else
            helm upgrade --install kubeblocks kubeblocks/kubeblocks \
              --version "$RELEASE_VERSION"
          fi
          
          helm list -A

      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.5.1
          go install github.com/onsi/gomega/...

      - name: run test
        run: |
          bash ${{ github.workspace }}/testinfra/.github/utils/change-wesql-cd.sh \
            ${{ github.workspace }}/testinfra ${{ github.event.inputs.change_flag }}
          
          cd testinfra
          make api-test TEST_MODULE=${{ github.event.inputs.test_module }}
