name: API-TEST-K3S

on:
  workflow_dispatch:
    inputs:
      TEST_MODULE:
        description: 'TEST_MODULE file or path'
        required: true
        default: ''
      CASE_NAME:
        description: 'test case name'
        required: false
        default: 'api-test-k3s'
      BRANCH_NAME:
        description: 'testinfra branch name'
        required: false
        default: 'main'
      RELEASE_VERSION:
        description: 'kubeblocks release version'
        required: false
        default: 'latest'
      CHAOS_INJECT:
        description: '1: install chaos-mesh'
        required: false
        default: ''
      CHANGE_FLAG:
        description: '2:change wesql cd fixed passwd'
        required: false
        default: ''

run-name: ${{ github.event.inputs.RELEASE_VERSION }}:${{ github.event.inputs.CASE_NAME }}

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  GO_VERSION: '1.19'
  HELM_VERSION: 'v3.10.0'
  K3D_NAME: default

jobs:
  k3s-api-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k3s: [ latest, v1.25, v1.24, v1.23, v1.22 ]
    name: K3s ${{matrix.k3s}}
    steps:
      - name: setup k3s
        uses: nolar/setup-k3d-k3s@v1
        with:
          k3d-name: ${{ env.K3D_NAME }}
          version: ${{ matrix.k3s }}
          github-token: ${{ env.GITHUB_TOKEN }}
          k3d-args: --no-lb --k3s-node-label topology.kubernetes.io/zone=cn-northwest-1a@server:0

      - name: install helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: checkout testinfra
        uses: actions/checkout@v3
        with:
          repository: apecloud/testinfra
          ref: ${{ github.event.inputs.BRANCH_NAME }}
          path: ./
          token: ${{ env.GITHUB_TOKEN }}

      - name: install dbaas
        run: |
          bash .github/utils/install-kubeblocks.sh ${{ github.event.inputs.RELEASE_VERSION }}

      - name: install chaos-mesh
        if: ${{ inputs.CHAOS_INJECT == 1 }}
        run: |
          helm repo add chaos-mesh https://charts.chaos-mesh.org
          helm upgrade --install --create-namespace chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing
          helm list -A

      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.5.1
          go install github.com/onsi/gomega/...

      - name: run test
        run: |
          bash .github/utils/change-wesql-cd.sh \
            ./ ${{ github.event.inputs.CHANGE_FLAG }}
          
          make api-test TEST_MODULE=${{ github.event.inputs.TEST_MODULE }}
