name: API-TEST-CHAOS-K3S

on:
  workflow_dispatch:
    inputs:
      test_module:
        description: 'TEST_MODULE file or path'
        required: true
        default: ''
      case_name:
        description: 'test case name'
        required: false
        default: 'api_test_k3s'
      branch_name:
        description: 'testinfra branch name'
        required: true
        default: 'main'
      release_version:
        description: 'kubeblocks release version'
        required: false
        default: 'latest'
      model:
        description: 'monitor:open monitor'
        required: false
        default: ''
      change_flag:
        description: '1:change wesql cd; 2:change wesql cd fixed passwd'
        required: false
        default: '1'

run-name: ${{ github.event.inputs.release_version }}:${{ github.event.inputs.case_name }}

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  GO_VERSION: '1.19'
  HELM_VERSION: 'v3.10.0'
  K3D_NAME: default

jobs:
  k3s-api-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k3s: [ latest, v1.25, v1.24, v1.23, v1.22 ]
    name: K3s ${{matrix.k3s}}
    steps:
      - uses: actions/checkout@v3
      - name: setup k3s
        uses: nolar/setup-k3d-k3s@v1
        with:
          k3d-name: ${{ env.K3D_NAME }}
          version: ${{ matrix.k3s }}
          github-token: ${{ env.GITHUB_TOKEN }}
          k3d-args: --agents 2 --no-lb --k3s-node-label topology.kubernetes.io/zone=cn-northwest-1b@agent:0 --k3s-node-label topology.kubernetes.io/zone=cn-northwest-1c@agent:1 --k3s-node-label topology.kubernetes.io/zone=cn-northwest-1a@server:0

      - name: show node labels
        run: |
          kubectl get nodes --show-labels

      - name: install helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: checkout testinfra
        uses: actions/checkout@v3
        with:
          repository: apecloud/testinfra
          ref: ${{ github.event.inputs.branch_name }}
          path: testinfra
          token: ${{ env.GITHUB_TOKEN }}

      - name: install dbaas
        run: |
          RELEASE_VERSION=`bash ${{ github.workspace }}/testinfra/.github/utils/release-version.sh ${{ env.GITHUB_TOKEN }} ${{ github.event.inputs.release_version }}`
          echo "RELEASE_VERSION:"$RELEASE_VERSION
          
          helm repo add kubeblocks https://apecloud.github.io/helm-charts

          MODEL=${{ github.event.inputs.model }}
          if [[ "$MODEL" == "monitor" ]]; then
            helm upgrade --install kubeblocks kubeblocks/kubeblocks \
              --version "$RELEASE_VERSION" \
              --set="prometheus.enabled=true" \
              --set="grafana.enabled=true" \
              --set="dashboards.enabled=true"
          else
            helm upgrade --install kubeblocks kubeblocks/kubeblocks \
              --version "$RELEASE_VERSION"
          fi
          
          helm list -A

      - name: install chaos-mesh
        run: |
          helm repo add chaos-mesh https://charts.chaos-mesh.org
          helm upgrade --install --create-namespace chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing
          helm list -A

      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.5.1
          go install github.com/onsi/gomega/...

      - name: run test
        run: |
          bash ${{ github.workspace }}/testinfra/.github/utils/change-wesql-cd.sh \
            ${{ github.workspace }}/testinfra ${{ github.event.inputs.change_flag }}
          
          cd testinfra
          make api-test TEST_MODULE=${{ github.event.inputs.test_module }}
