name: Deploy AWS EKS

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  deploy-aws-eks:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: "cn-northwest-1"

      - name: checkout cloud-provider
        uses: actions/checkout@v3
        with:
          repository: apecloud/cloud-provider
          ref: "apecd-deploy"
          path: cloud-provider
          token: ${{ env.GITHUB_TOKEN }}

      - name: run test
        run: |
          cd cloud-provider/aws/eks-default-vpc
          mv terraform.tfvars.arm64 terraform.tfvars
          bash run.sh
