name: Deploy AWS EKS

on:
  workflow_dispatch:
    inputs:
      CLUSTER_VERSION:
        description: 'eks cluster version (e.g. 1.25)'
        required: false
        default: ''
      INSTANCE_TYPE:
        description: 'node instance types (e.g. amd64/arm64)'
        required: false
        default: 'amd64'

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: cn-northwest-1

permissions:
  id-token: write
  contents: read


jobs:
  init-aws-eks:
    uses: ./.github/workflows/terraform-init.yml
    with:
      cluster-version: ${{ inputs.CLUSTER_VERSION }}
      instance-type: ${{ inputs.INSTANCE_TYPE }}
      artifact-name: aws-eks-${{ github.sha }}
    secrets: inherit

  destroy-aws-eks:
    if: ${{ always() }}
    needs: init-aws-eks
    uses: ./.github/workflows/terraform-destroy.yml
    with:
      artifact-name: aws-eks-${{ github.sha }}
    secrets: inherit
