name: KBCLI-TEST-SCHEDULE

on:
#  schedule:
#    - cron: '0 16 * * *'
  workflow_dispatch:
    inputs:
      release_version:
        description: 'kubeblocks release version'
        required: false
        default: 'latest'
      branch_name:
        description: 'testinfra branch name'
        required: false
        default: 'main'
      test_type:
        description: 'test type (1:mysql 2:pg 3:kb upgrade 4:playground or 1|2|3|4)'
        required: true
        default: '1|2'
run-name: kbcli test ${{ inputs.release_version }}

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  HELM_VERSION: 'v3.10.0'


jobs:
  kbcli-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s: [ v1.25.5, v1.24.9, v1.23.15, v1.22.16 ]
    name: Minikube ${{matrix.k8s}}
    env:
      K8S: ${{ matrix.k8s }}
    steps:
      - uses: azure/setup-kubectl@v3
        with:
          version: "${{ matrix.k8s }}"

      - name: checkout testinfra
        uses: actions/checkout@v3
        with:
          repository: apecloud/testinfra
          ref: ${{ inputs.branch_name }}
          path: ./
          token: ${{ env.GITHUB_TOKEN }}

      - name: setup minikube
        if: inputs.test_type != 4
        uses: medyagh/setup-minikube@latest
        id: minikube
        with:
          cache: false
          kubernetes-version: ${{ matrix.k8s }}
          cpus: 2
          memory: 4096m

      - name: run kbcli test
        run: |
          bash .github/utils/kbcli-test-schedule.sh \
            ${{ inputs.test_type }} \
            ${{ inputs.release_version }}
