name: Test KBCLI on EKS

on:
  workflow_dispatch:
    inputs:
      CLUSTER_VERSION:
        description: 'eks cluster version (e.g. 1.25)'
        required: false
        default: ''
      INSTANCE_TYPE:
        description: 'node instance types (e.g. amd64/arm64)'
        required: false
        default: 'amd64'
      KB_VERSION:
        description: 'kubeblocks release version'
        required: false
        default: 'latest'

run-name: kbcli test ${{ inputs.CLUSTER_VERSION }} ${{ inputs.INSTANCE_TYPE }}

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  init-aws-eks:
    uses: ./.github/workflows/terraform-init.yml
    with:
      cluster-version: ${{ inputs.CLUSTER_VERSION }}
      instance-type: ${{ inputs.INSTANCE_TYPE }}
      artifact-name: aws-eks-${{ github.sha }}
      deploy-path: ./aws/eks-default-vpc
    secrets: inherit

  test-mysql:
    if: ${{ needs.init-aws-eks.result == "success" }}
    needs: init-aws-eks
    uses: ./.github/workflows/test-kbcli.yml
    with:
      release-version: "${{ inputs.KB_VERSION }}"
      test-type: "1"
      test-args: "--enable-termination-policy false --upgrade true "
      eks-cluster-name: ${{ needs.init-aws-eks.outputs.eks-cluster-name }}
    secrets: inherit

  test-postgresql:
    if: ${{ always() && needs.init-aws-eks.result == "success" }}
    needs: [init-aws-eks,test-mysql]
    uses: ./.github/workflows/test-kbcli.yml
    with:
      release-version: "${{ inputs.KB_VERSION }}"
      test-type: "2"
      test-args: "--enable-termination-policy false --upgrade false --config-s3 false"
      eks-cluster-name: ${{ needs.init-aws-eks.outputs.eks-cluster-name }}
    secrets: inherit

  test-redis:
    if: ${{ always() && needs.init-aws-eks.result == "success" }}
    needs: [init-aws-eks,test-postgresql]
    uses: ./.github/workflows/test-kbcli.yml
    with:
      release-version: "${{ inputs.KB_VERSION }}"
      test-type: "5"
      test-args: "--enable-termination-policy false --upgrade false --config-s3 false"
      eks-cluster-name: ${{ needs.init-aws-eks.outputs.eks-cluster-name }}
    secrets: inherit

  test-mongodb:
    if: ${{ always() && needs.init-aws-eks.result == "success" }}
    needs: [init-aws-eks,test-redis]
    uses: ./.github/workflows/test-kbcli.yml
    with:
      release-version: "${{ inputs.KB_VERSION }}"
      test-type: "6"
      test-args: "--enable-termination-policy false --upgrade false --config-s3 false"
      eks-cluster-name: ${{ needs.init-aws-eks.outputs.eks-cluster-name }}
    secrets: inherit

  destroy-aws-eks:
    if: ${{ always() }}
    needs: [init-aws-eks,test-mongodb]
    uses: ./.github/workflows/terraform-destroy.yml
    with:
      artifact-name: aws-eks-${{ github.sha }}
      deploy-path: ./aws/eks-default-vpc
    secrets: inherit
