name: RELEASE-IMAGE

on:
  workflow_call:
    inputs:
      MAKE_OPS:
        description: "The ops name of makefile (default: push-image)"
        required: true
        default: "push-image"
      IMG:
        description: "The URL to use building/pushing image targets (e.g. apecloud/kubeblocks)"
        required: true
        default: ""
      TAG_NAME:
        description: "The tag name of image (default: latest)"
        required: true
        default: "latest"
      BUILDX_ENABLED:
        description: "Image tag name (default: true)"
        required: false
        default: "true"
      DOCKER_USERNAME:
        description: "The username of docker.io"
        required: false
        default: ""
      DOCKER_PASSWORD:
        description: "The password of docker.io"
        required: false
        default: ""
      ALIYUN_USERNAME:
        description: "The username of aliyun"
        required: false
        default: ""
      ALIYUN_PASSWORD:
        description: "The password of aliyun"
        required: false
        default: ""
      GO_VERSION:
        description: "Install the specify version of go"
        required: false
        default: ""

env:
  DOCKER_REGISTRY_URL: docker.io
  ALIYUN_REGISTRY_URL: registry.cn-hangzhou.aliyuncs.com

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master

      - name: Setup Go
        if: ${{ "${{ inputs.GO_VERSION }}" != "" }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.GO_VERSION }}

      - name: Build and Push to docker.io
        if: ${{ "${{ inputs.DOCKER_USERNAME }}" != "" && "${{ inputs.DOCKER_PASSWORD }}" != "" }}
        run: |
          docker login \
            --username "${{ inputs.DOCKER_USERNAME }}" \
            --password "${{ inputs.DOCKER_PASSWORD }}" \
            ${{ env.DOCKER_REGISTRY_URL }}
          
          make ${{ inputs.MAKE_OPS }} \
              VERSION="${{ inputs.TAG_NAME }}" \
              BUILDX_ENABLED=${{ inputs.BUILDX_ENABLED }} \
              IMG=${{ env.DOCKER_REGISTRY_URL }}/${{ inputs.IMG }} \
              BUILDX_ARGS="--sbom=false --provenance=false"

      - name: Build and Push to aliyun
        if: ${{ "${{ inputs.ALIYUN_USERNAME }}" != "" && "${{ inputs.ALIYUN_PASSWORD }}" != "" }}
        run: |
          docker login \
              --username "${{ inputs.ALIYUN_USERNAME }}" \
              --password "${{ inputs.ALIYUN_PASSWORD }}" \
              ${{ env.ALIYUN_REGISTRY_URL }}
          
          make ${{ inputs.MAKE_OPS }} \
              VERSION="${{ inputs.TAG_NAME }}" \
              BUILDX_ENABLED=${{ inputs.BUILDX_ENABLED }} \
              IMG=${{ env.ALIYUN_REGISTRY_URL }}/${{ inputs.IMG }} \
              BUILDX_ARGS="--sbom=false --provenance=false"
