name: skopeo sync kubeblocks

on:
  workflow_dispatch:
    inputs:
      sync_flag:
        description: 'sync flag'
        required: false
        default: '1'
jobs:
  script:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name : skopeo sync kubeblocks
        run: |
          brew install skopeo
          skopeo sync -h
          if [[ ! -z "${{ github.event.inputs.sync_flag }}" ]];then
            bash ${{ github.workspace }}/.github/utils/skopeo_copy.sh \
              "${{ secrets.DOCKER_USER }}" '${{ secrets.DOCKER_PASSWORD }}' \
              "${{ secrets.ALIYUN_USER }}" "${{ secrets.ALIYUN_PASSWORD }}" \
              ${{ github.workspace }}/.github/utils/images-kubeblocks-list.txt
          else
            skopeo sync --all \
              --src-creds "${{ secrets.DOCKER_USER }}:${{ secrets.DOCKER_PASSWORD }}" \
              --dest-creds "${{ secrets.ALIYUN_USER }}:${{ secrets.ALIYUN_PASSWORD }}" \
              --src docker \
              --dest docker \
              docker.io/apecloud/kubeblocks \
              registry.cn-hangzhou.aliyuncs.com/apecloud
          fi
          
