name: skopeo sync images

on:
  workflow_dispatch:
    inputs:
      images_name:
        description: 'sync images name e.g. apecloud/kubeblocks:0.3.8'
        required: false
        default: ''
jobs:
  script:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name : skopeo sync images
        run: |
          brew install skopeo
          skopeo sync -h
          if [[ ! -z "${{ github.event.inputs.images_name }}" ]];then
              echo "${{ github.event.inputs.images_name }}" > ${{ github.workspace }}/.github/utils/images-list.txt
          fi
          
          bash ${{ github.workspace }}/.github/utils/skopeo_sync.sh \
              "${{ secrets.DOCKER_USER }}" \
              '${{ secrets.DOCKER_PASSWORD }}' \
              "${{ secrets.ALIYUN_USER }}" \
              "${{ secrets.ALIYUN_PASSWORD }}" \
              ${{ github.workspace }}/.github/utils/images-list.txt 
