name: skopeo copy images to docker.io

on:
  workflow_dispatch:
    inputs:
      images_name:
        description: 'copy images name e.g. apecloud/kubeblocks:0.3.8'
        required: false
        default: ''
      registry:
        description: 'copy images registry e.g. docker.io'
        required: false
        default: 'docker.io'

run-name: copy to docker.io:${{ github.event.inputs.images_name }}

env:
  DOCKER_REGISTRY_URL: docker.io
  DOCKER_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

jobs:
  script:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - if: ${{ github.event.inputs.registry == 'docker.io' && env.DOCKER_USER != '' && env.DOCKER_PASSWORD != '' }}
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name : skopeo copy images
        run: |
          brew install skopeo
          skopeo copy -h
          if [[ ! -z "${{ github.event.inputs.images_name }}" ]];then
              bash ${{ github.workspace }}/.github/utils/utils.sh \
                  --type 1 \
                  --images "${{ github.event.inputs.images_name }}" \
                  --images-list ${{ github.workspace }}/.github/utils/images-list.txt
          fi
          
          bash ${{ github.workspace }}/.github/utils/skopeo_copy_to_docker.sh \
              "${{ secrets.DOCKER_USER }}" \
              '${{ secrets.DOCKER_PASSWORD }}' \
              ${{ github.workspace }}/.github/utils/images-list.txt \
              "${{ github.event.inputs.registry }}"
