name: Terrafrom Destroy

on:
  workflow_call:
    inputs:
      deploy-path:
        description: 'terraform deploy path'
        type: string
        required: false
        default: ''
      artifact-name:
        description: 'terraform artifact name'
        type: string
        required: false
        default: ''

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: cn-northwest-1

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: "${{ env.AWS_DEFAULT_REGION }}"

      - name: checkout cloud-provider
        uses: actions/checkout@v3
        with:
          repository: apecloud/cloud-provider
          ref: "apecd-deploy"
          path: ./
          token: ${{ env.GITHUB_TOKEN }}

      - name: download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.deploy-path }}

      - name: terraform destroy
        run: |
          cd ${{ inputs.deploy-path }}
          bash run.sh --type 2

  remove-artifact:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: terraform-destroy
    steps:
      - name: remove artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
