name: Terrafrom init

on:
  workflow_call:
    inputs:
      cluster-version:
        description: 'eks cluster version (e.g. 1.25)'
        type: string
        required: false
        default: ''
      instance-type:
        description: 'node instance types (e.g. amd64/arm64)'
        type: string
        required: false
        default: 'amd64'
      deploy-path:
        description: 'terraform deploy path'
        type: string
        required: false
        default: ''
      artifact-name:
        description: 'terraform artifact name'
        type: string
        required: false
        default: ''

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: cn-northwest-1

permissions:
  id-token: write
  contents: read

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: "${{ env.AWS_DEFAULT_REGION }}"

      - name: checkout cloud-provider
        uses: actions/checkout@v3
        with:
          repository: apecloud/cloud-provider
          ref: "apecd-deploy"
          path: ./
          token: ${{ env.GITHUB_TOKEN }}

      - name: terraform init aws eks
        run: |
          cd ${{ inputs.deploy-path }}
          bash run.sh --type 1 \
              --cluster-version ${{ inputs.cluster-version }} \
              --instance-type ${{ inputs.instance-type }}

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.deploy-path }}
          retention-days: 1
