name: TEST-KBCLI

on:
  workflow_call:
    inputs:
      release-version:
        description: 'kubeblocks release version'
        type: string
        required: false
        default: 'latest'
      branch-name:
        description: 'testinfra branch name'
        type: string
        required: false
        default: 'main'
      test-type:
        description: 'test type (1:mysql 2:postgresql 5:redis 6:mongodb)'
        type: string
        required: false
        default: '1|2|5|6'
      test-args:
        description: 'test args'
        type: string
        required: false
        default: ''
      region:
        description: 'terraform artifact name'
        type: string
        required: false
        default: 'cn-northwest-1'
      eks-cluster-name:
        description: 'eks cluster name'
        type: string
        required: false
        default: ''

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_PATH: testinfra/kbcli-test/${{ inputs.test-type }}/${{ inputs.release-version }}

permissions:
  id-token: write
  contents: read

jobs:
  kbcli-test:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: "${{ inputs.region }}"

      - name: checkout testinfra
        uses: actions/checkout@v3
        with:
          repository: apecloud/testinfra
          ref: ${{ inputs.branch-name }}
          path: ./
          token: ${{ env.GITHUB_TOKEN }}

      - name: run kbcli test
        run: |
          file_log="$(date +%Y-%m-%d-%T)".log
          
          bash .github/utils/kbcli-test.sh \
            --type ${{ inputs.test-type }} \
            --kubeblocks-version ${{ inputs.release-version }} \
            --args "${{ inputs.test-args }}" \
            --region "${{ inputs.region }}" \
            --cluster-name ${{ inputs.eks-cluster-name }} | tee $file_log
          
          mkdir -p ${{ env.S3_PATH }}
          cp $file_log ${{ env.S3_PATH }}

      - uses: shallwefootball/s3-upload-action@master
        name: upload logs to S3
        with:
          aws_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ vars.AWS_S3_BUCKET }}
          source_dir: '${{ env.S3_PATH }}'
          destination_dir: '${{ env.S3_PATH }}'
          endpoint: "${{ vars.AWS_S3_ENDPOINT }}"
